// Generated by playautomation. Replay with: npx tsx <file> (or playautomation run)
import { chromium } from 'playwright-core';

const inputs = {
  "email": "demo@test.shop",
  "password": "demo123"
} as const;


function resolveTemplate(value: string, inputs: Record<string, string>): string {
  return value.replace(/\{\{\s*([\w.-]+)\s*\}\}/g, (whole, name: string) => {
    if (!(name in inputs)) throw new Error(`Unknown input ${name}`);
    return inputs[name];
  });
}

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto("http://127.0.0.1:8931/login.html");
  { // fill testid="login-email"
    const value = resolveTemplate("{{email}}", inputs);
    await page.getByTestId("login-email").fill(value);
  }
  { // fill testid="login-password"
    const value = resolveTemplate("{{password}}", inputs);
    await page.getByTestId("login-password").fill(value);
  }
  await page.getByRole("heading", { name: "Sign in" }).click();
  await page.getByTestId("login-submit").click();
  await assert(page.getByText("Dashboard") !== null);
  await page.goto("http://127.0.0.1:8931/login.html");
  { // fill testid="login-email"
    const value = resolveTemplate("{{email}}", inputs);
    await page.getByTestId("login-email").fill(value);
  }
  await page.getByRole("heading", { name: "Sign in" }).click();
  await page.locator("h1").waitFor({ state: 'visible' });
  { // fill testid="login-password"
    const value = resolveTemplate("{{password}}", inputs);
    await page.getByTestId("login-password").fill(value);
  }
  await page.getByTestId("login-submit").click();
  await assert(page.getByText("Dashboard") !== null);
  if (!page.url().includes("welcome")) throw new Error('URL assertion failed');
  await page.screenshot({ path: 'screenshot-s15.png', fullPage: true });
  await browser.close();
})().catch(error => {
  console.error(error);
  process.exit(1);
});
