// Generates a standalone TypeScript script from a flow.
// Shape follows playwright-main/packages/isomorphic/codegen/javascript.ts,
// but emits playwright-core library usage (no test runner dependency).

import type { Flow } from '../flow.js';
import { locatorExpr } from '../runner/selectors.js';

export function generateFlowScript(flow: Flow): string {
  const lines: string[] = [];
  lines.push('// Generated by playautomation. Replay with: npx tsx <file> (or playautomation run)');
  lines.push("import { chromium } from 'playwright-core';");
  lines.push('');
  lines.push(`const inputs = ${JSON.stringify(flow.inputs, null, 2)} as const;`);
  lines.push('');
  if (scriptNeedsTemplateHelper(flow))
    lines.push(templateHelperSource);
  lines.push('(async () => {');
  lines.push('  const browser = await chromium.launch();');
  lines.push('  const page = await browser.newPage();');
  for (const step of flow.steps)
    lines.push(...stepLines(step));
  lines.push('  await browser.close();');
  lines.push('})().catch(error => {');
  lines.push('  console.error(error);');
  lines.push('  process.exit(1);');
  lines.push('});');
  return lines.join('\n') + '\n';
}

function stepLines(step: Flow['steps'][number]): string[] {
  switch (step.kind) {
    case 'goto':
      return [`  await page.goto(${JSON.stringify(step.url)});`];
    case 'click':
      return [`  await ${locatorExpr(step.selector!)}.click();`];
    case 'hover':
      return [`  await ${locatorExpr(step.selector!)}.hover();`];
    case 'check':
      return [`  await ${locatorExpr(step.selector!)}.check();`];
    case 'uncheck':
      return [`  await ${locatorExpr(step.selector!)}.uncheck();`];
    case 'fill':
      return [
        `  { // fill ${step.selector}`,
        `    const value = resolveTemplate(${JSON.stringify(step.text)}, inputs);`,
        `    await ${locatorExpr(step.selector!)}.fill(value);`,
        `  }`,
      ];
    case 'select':
      return [`  await ${locatorExpr(step.selector!)}.selectOption(${JSON.stringify(step.values)});`];
    case 'press':
      return [`  await page.keyboard.press(${JSON.stringify(step.key)});`];
    case 'wait': {
      const w = step.wait!;
      if (w.kind === 'ms')
        return [`  await page.waitForTimeout(${parseInt(w.value, 10) || 0});`];
      if (w.kind === 'url')
        return [`  await page.waitForURL(${JSON.stringify(w.value)}, { timeout: ${w.timeoutMs ?? 10000} });`];
      if (w.kind === 'text')
        return [`  await page.getByText(${JSON.stringify(w.value)}).waitFor({ timeout: ${w.timeoutMs ?? 10000} });`];
      return [`  await ${locatorExpr(w.value)}.waitFor({ timeout: ${w.timeoutMs ?? 10000} });`];
    }
    case 'screenshot':
      return [`  await page.screenshot({ path: 'screenshot-${step.id}.png', fullPage: true });`];
    case 'assert': {
      const a = step.assert!;
      if (a.kind === 'text')
        return [`  await assert(page.getByText(${JSON.stringify(a.expected)}) !== null);`];
      const expr = a.target ? locatorExpr(a.target) : 'page';
      if (a.kind === 'visible')
        return [`  await ${expr}.waitFor({ state: 'visible' });`];
      if (a.kind === 'hidden')
        return [`  await ${expr}.waitFor({ state: 'hidden' });`];
      if (a.kind === 'url')
        return [`  if (!page.url().includes(${JSON.stringify(a.expected)})) throw new Error('URL assertion failed');`];
      return [`  await assertValue(${expr}, ${JSON.stringify(a.expected)});`];
    }
  }
  return [];
}

// resolveTemplate helper is emitted only when the flow has templated text.
export function scriptNeedsTemplateHelper(flow: Flow): boolean {
  return flow.steps.some(s => s.text?.includes('{{'));
}

export const templateHelperSource = `
function resolveTemplate(value: string, inputs: Record<string, string>): string {
  return value.replace(/\\{\\{\\s*(env:([\\w.-]+)|[\\w.-]+)\\s*\\}\\}/g, (whole, name: string, envName?: string) => {
    if (envName !== undefined) {
      const v = process.env[envName];
      if (v === undefined) throw new Error(\`Environment variable "\${envName}" is not set (referenced by \${whole})\`);
      return v;
    }
    if (!(name in inputs)) throw new Error(\`Unknown input "\${name}" referenced by template \${whole}\`);
    const resolved = inputs[name];
    return resolved.includes('{{env:') ? resolveTemplate(resolved, inputs) : resolved;
  });
}
`;
