// Case matrix: input variants replayed against one flow.
// Sources: an explicit <flow>.cases.yaml (typically authored by the agent),
// or rule-generated variants (empty-string per text input) as the baseline.

import * as fs from 'node:fs';
import * as path from 'node:path';
import { stringify as stringifyYaml } from 'yaml';
import type { Flow } from '../flow.js';
import { loadCasesFile, type CasesFile } from '../spec.js';

export interface CaseSpec {
  name: string;
  inputs: Record<string, string>;
  expectFail?: boolean;
}

export type CaseSource = 'file' | 'rules' | 'default';

export function buildRuleCases(flow: Flow): CaseSpec[] {
  const cases: CaseSpec[] = [];
  for (const key of Object.keys(flow.inputs)) {
    cases.push({ name: `empty-${key}`, inputs: { [key]: '' } });
  }
  return cases;
}

export function loadCasesForFlow(flowFile: string, flow: Flow, explicitFlag: string | undefined): { cases: CaseSpec[]; source: CaseSource; casesFile?: string } {
  const defaultCase: CaseSpec = { name: 'default', inputs: {} };
  if (explicitFlag === 'none')
    return { cases: [defaultCase], source: 'default' };

  const candidates = explicitFlag
    ? [explicitFlag]
    : [flowFile.replace(/\.flow\.json$/, '') + '.cases.yaml', flowFile.replace(/\.json$/, '') + '.cases.yaml'];
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      const parsed: CasesFile = loadCasesFile(candidate);
      const cases = parsed.cases.map(c => ({ name: c.name, inputs: c.inputs ?? {}, expectFail: c.expectFail }));
      return { cases, source: 'file', casesFile: candidate };
    }
  }
  if (explicitFlag)
    throw new Error(`Cases file not found: ${explicitFlag}`);

  const rules = buildRuleCases(flow);
  if (rules.length)
    return { cases: [defaultCase, ...rules], source: 'rules' };
  return { cases: [defaultCase], source: 'default' };
}

export function casesFilePathFor(flowFile: string): string {
  return flowFile.replace(/\.flow\.json$/, '').replace(/\.json$/, '') + '.cases.yaml';
}

export function writeCasesFile(flowFile: string, cases: CaseSpec[]): string {
  const file = casesFilePathFor(flowFile);
  const body: CasesFile = { cases: cases.map(c => ({ name: c.name, inputs: c.inputs, ...(c.expectFail ? { expectFail: true } : {}) })) };
  fs.mkdirSync(path.dirname(path.resolve(file)), { recursive: true });
  fs.writeFileSync(file, '# Generated by `playautomation cases --save`\n' + stringifyYaml(body));
  return file;
}
